// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentWepApi.Data.UserContext;

public partial class TOKEN_MANAGEMENT
{
    public int ID { get; set; }

    public int USER_ID { get; set; }

    public string TOKEN { get; set; }

    public DateTime EXPIRES_AT { get; set; }

    public DateTime CREATED_AT { get; set; }

    public int REVOKED { get; set; }

    public string REPLACED_BY_TOKEN { get; set; }
}