// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentWepApi.Data.UserContext;

public partial class USER
{
    public int ID { get; set; }

    public string USER_NAME { get; set; }

    public string EMAIL { get; set; }

    public string PASSWORD { get; set; }

    public int IS_ACTIVE { get; set; }

    public DateTime CREATED_ON { get; set; }
}