// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace StudentWepApi.Data.UserContext;

public partial class UserDbContext : DbContext
{
    public UserDbContext(DbContextOptions<UserDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TOKEN_MANAGEMENT> TOKEN_MANAGEMENT { get; set; }

    public virtual DbSet<USER> USER { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TOKEN_MANAGEMENT>(entity =>
        {
            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CREATED_AT).HasColumnType("datetime");
            entity.Property(e => e.EXPIRES_AT).HasColumnType("datetime");
            entity.Property(e => e.TOKEN).IsRequired();
        });

        modelBuilder.Entity<USER>(entity =>
        {
            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CREATED_ON).HasColumnType("datetime");
            entity.Property(e => e.EMAIL)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PASSWORD).IsRequired();
            entity.Property(e => e.USER_NAME)
                .IsRequired()
                .HasMaxLength(200);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}