// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentWepApi.Data.StudentContext;

public partial class document_joy
{
    public long id { get; set; }

    public string name { get; set; }

    public string type { get; set; }

    public int size { get; set; }

    public long student_id { get; set; }

    public string file_name { get; set; }

    public string original_file_name { get; set; }

    public virtual student_joy student { get; set; }
}