// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentWepApi.Data.StudentContext;

public partial class state_joy
{
    public long id { get; set; }

    public string name { get; set; }

    public bool? is_active { get; set; }

    public virtual ICollection<city_joy> city_joy { get; set; } = new List<city_joy>();

    public virtual ICollection<student_joy> student_joy { get; set; } = new List<student_joy>();
}