// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentWepApi.Data.StudentContext;

public partial class student_marksList_joy
{
    public long id { get; set; }

    public long student_id { get; set; }

    public long subject_id { get; set; }

    public decimal marks { get; set; }

    public virtual student_joy student { get; set; }

    public virtual subject_joy subject { get; set; }
}