// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentWepApi.Data.StudentContext;

public partial class student_joy
{
    public long id { get; set; }

    public string first_name { get; set; }

    public string last_name { get; set; }

    public long state_id { get; set; }

    public long city_id { get; set; }

    public DateOnly dob { get; set; }

    public string mobile { get; set; }

    public string email_id { get; set; }

    public long age { get; set; }

    public string code { get; set; }

    public bool? is_active { get; set; }

    public virtual city_joy city { get; set; }

    public virtual ICollection<document_joy> document_joy { get; set; } = new List<document_joy>();

    public virtual state_joy state { get; set; }

    public virtual ICollection<student_marksList_joy> student_marksList_joy { get; set; } = new List<student_marksList_joy>();
}