// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace StudentWepApi.Data.StudentContext;

public partial class StudentDbContext : DbContext
{
    public StudentDbContext(DbContextOptions<StudentDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<city_joy> city_joy { get; set; }

    public virtual DbSet<document_joy> document_joy { get; set; }

    public virtual DbSet<state_joy> state_joy { get; set; }

    public virtual DbSet<student_joy> student_joy { get; set; }

    public virtual DbSet<student_marksList_joy> student_marksList_joy { get; set; }

    public virtual DbSet<subject_joy> subject_joy { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<city_joy>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__city_joy__3213E83FBAC6088B");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.is_active).HasDefaultValue(true);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.state).WithMany(p => p.city_joy)
                .HasForeignKey(d => d.state_id)
                .HasConstraintName("FK__city_joy__state___06CD04F7");
        });

        modelBuilder.Entity<document_joy>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__document__3213E83F0EDD0893");

            entity.Property(e => e.file_name)
                .HasMaxLength(355)
                .IsUnicode(false);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.original_file_name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.type)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.student).WithMany(p => p.document_joy)
                .HasForeignKey(d => d.student_id)
                .HasConstraintName("FK__document___stude__19DFD96B");
        });

        modelBuilder.Entity<state_joy>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__state_jo__3213E83FF5430422");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.is_active).HasDefaultValue(true);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<student_joy>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__student___3213E83F97A145D5");

            entity.HasIndex(e => e.email_id, "UQ__student___3FEF8767DA0F0B8B").IsUnique();

            entity.HasIndex(e => e.mobile, "UQ__student___A32E2E1CBA4119AB").IsUnique();

            entity.Property(e => e.code)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.email_id)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.first_name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.is_active).HasDefaultValue(true);
            entity.Property(e => e.last_name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.mobile)
                .IsRequired()
                .HasMaxLength(13)
                .IsUnicode(false);

            entity.HasOne(d => d.city).WithMany(p => p.student_joy)
                .HasForeignKey(d => d.city_id)
                .HasConstraintName("FK__student_j__city___0D7A0286");

            entity.HasOne(d => d.state).WithMany(p => p.student_joy)
                .HasForeignKey(d => d.state_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__student_j__state__0C85DE4D");
        });

        modelBuilder.Entity<student_marksList_joy>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__student___3213E83FF64974F5");

            entity.Property(e => e.marks).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.student).WithMany(p => p.student_marksList_joy)
                .HasForeignKey(d => d.student_id)
                .HasConstraintName("FK__student_m__stude__1332DBDC");

            entity.HasOne(d => d.subject).WithMany(p => p.student_marksList_joy)
                .HasForeignKey(d => d.subject_id)
                .HasConstraintName("FK__student_m__subje__14270015");
        });

        modelBuilder.Entity<subject_joy>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__subject___3213E83F5356D987");

            entity.Property(e => e.is_active).HasDefaultValue(true);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}