// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentWepApi.Data.StudentContext;

public partial class subject_joy
{
    public long id { get; set; }

    public string name { get; set; }

    public bool? is_active { get; set; }

    public virtual ICollection<student_marksList_joy> student_marksList_joy { get; set; } = new List<student_marksList_joy>();
}